<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>agv_sim</name>
  <version>0.0.0</version>
  <description>Simulasi AGV dengan Gazebo Harmonic</description>
  <maintainer email="febryan@todo.todo">Febryan</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>ros_gz</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>pointcloud_concatenate</exec_depend>
  <exec_depend>localization</exec_depend>
  <exec_depend>agv_robot_description</exec_depend>
  <exec_depend>agv_robot_gazebo</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
    <gz_sim_resource_path>${prefix}/..</gz_sim_resource_path>
  </export>
</package>
