<?xml version="1.0"?>
<package format="3">
  <name>agv_robot_gazebo</name>
  <version>0.0.0</version>
  <description>AGV robot simulation in Gazebo Harmonic</description>
  <maintainer email="febryan@todo.todo">febryan</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>ros_gz_sim</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
